import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// read store
const storePath = join(import.meta.dir, "apps/auth-portal/data/profiles.json");
const store = JSON.parse(readFileSync(storePath, "utf-8"));

const DOCKER_COMPOSE_PATH = join(import.meta.dir, "apps/code-server-infra/docker-compose.yml");
const CODE_SERVER_IMAGE = "lscr.io/linuxserver/code-server:latest";

const services: string[] = [];

for (const profile of store.profiles) {
  const serviceName = `hermes-ide-${profile.name}`;
  const apiPort = profile.port + 10000;
  
  // get generated key
  let apiKey = profile.password;
  try {
     apiKey = require('crypto').createHash('sha256').update(profile.name + '2025_hermes_secret_key').digest('hex');
  } catch(e){}
  
  services.push(`  ${serviceName}:
    image: ${CODE_SERVER_IMAGE}
    container_name: ${serviceName}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD=${profile.password}
      - DEFAULT_WORKSPACE=/projects
      - HERMES_API_URL=http://103.196.116.213:${apiPort}/v1
      - HERMES_API_KEY=${apiKey}
    volumes:
      - /home/ade/projects/${profile.name}:/projects
      - ./config-${profile.name}:/config
      - /home/ade/projects/rio/hermes-ide-extension/apps/extension:/hermes-extension:ro
    ports:
      - "${profile.port}:8443"
    networks:
      - hermes-ide-net
    restart: unless-stopped`);
}

const content = `# AUTO-GENERATED by Auth Portal API — DO NOT EDIT MANUALLY
# Generated at: ${new Date().toISOString()}

networks:
  hermes-ide-net:
    driver: bridge

services:
${services.join("\n\n")}
`;

writeFileSync(DOCKER_COMPOSE_PATH, content);
console.log("Written compose");
