import { writeFileSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import type { ProfileStore } from "./store";

const DOCKER_COMPOSE_PATH = join(import.meta.dir, "../../../code-server-infra/docker-compose.yml");

// Nginx config paths
const NGINX_TMP_PATH = "/tmp/hermes-ide-nginx.conf";
const NGINX_SITES_PATH = "/etc/nginx/sites-available/ide.app.dev.nusa.work";
const NGINX_ENABLED_PATH = "/etc/nginx/sites-enabled/ide.app.dev.nusa.work";

// SSL & domain config
const IDE_DOMAIN = "app.dev.nusa.work";          // parent domain (wildcard cert covers *.app.dev.nusa.work)
const AUTH_PORTAL_DOMAIN = "ide.app.dev.nusa.work"; // Auth Portal subdomain
const SSL_CERT = "/etc/letsencrypt/live/app.dev.nusa.work-0001/fullchain.pem";
const SSL_KEY = "/etc/letsencrypt/live/app.dev.nusa.work-0001/privkey.pem";
const AUTH_PORTAL_PORT = 51000;

const CODE_SERVER_IMAGE = "lscr.io/linuxserver/code-server:latest";
const HERMES_PROFILES_DIR = "/home/ade/.hermes/profiles";

/**
 * Read API_SERVER_KEY from a Hermes profile's .env file.
 * Falls back to profile password if .env doesn't exist or key not set.
 */
function getHermesApiKey(profileName: string, fallback: string): string {
  const envPath = join(HERMES_PROFILES_DIR, profileName, ".env");
  try {
    if (!existsSync(envPath)) return fallback;
    const content = readFileSync(envPath, "utf-8");
    const match = content.match(/^API_SERVER_KEY=(.+)$/m);
    return match ? match[1].trim() : fallback;
  } catch {
    return fallback;
  }
}

// ─────────────────────────────────────────────
// Docker Compose generation
// ─────────────────────────────────────────────

export function generateDockerCompose(store: ProfileStore): string {
  const services: string[] = [];

  for (const profile of store.profiles) {
    const serviceName = `hermes-ide-${profile.name}`;
    const apiPort = profile.port + 10000;
    const hermesApiKey = getHermesApiKey(profile.name, profile.password);
    
    const mcpPort = profile.port + 5000; // MCP service port on host
    
    services.push(`  ${serviceName}:
    image: ${CODE_SERVER_IMAGE}
    container_name: ${serviceName}
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
      - PASSWORD=${profile.password}
      - DEFAULT_WORKSPACE=/projects
      - HERMES_API_URL=http://103.196.116.213:${apiPort}/v1
      - HERMES_API_KEY=${hermesApiKey}
      - MCP_SERVICE_URL=http://host.docker.internal:${mcpPort}
      - HOST_PROJECTS_BASE=/home/ade/projects/${profile.name}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/ade/projects/${profile.name}:/projects
      - ./config-${profile.name}:/config
    ports:
      - "${profile.port}:8443"
    networks:
      - hermes-ide-net
    restart: unless-stopped`);
  }

  return `# AUTO-GENERATED by Auth Portal API — DO NOT EDIT MANUALLY
# Generated at: ${new Date().toISOString()}

networks:
  hermes-ide-net:
    driver: bridge

services:
${services.join("\n\n")}
`;
}

export function writeDockerCompose(store: ProfileStore): void {
  const content = generateDockerCompose(store);
  writeFileSync(DOCKER_COMPOSE_PATH, content);
}

export async function restartContainer(serviceName: string): Promise<{ success: boolean; output: string }> {
  const cwd = join(import.meta.dir, "../../../code-server-infra");
  // using --no-deps to only recreate the specified container
  const upProc = Bun.spawn(["docker", "compose", "up", "-d", "--no-deps", serviceName], { cwd, stdout: "pipe", stderr: "pipe" });
  const upOutput = await new Response(upProc.stdout).text();
  const upErr = await new Response(upProc.stderr).text();
  const exitCode = await upProc.exited;

  return {
    success: exitCode === 0,
    output: [upOutput, upErr].filter(Boolean).join("\n"),
  };
}

export async function restartContainers(): Promise<{ success: boolean; output: string }> {
  const cwd = join(import.meta.dir, "../../../code-server-infra");
  const proc = Bun.spawn(["docker", "compose", "down", "--remove-orphans"], { cwd, stdout: "pipe", stderr: "pipe" });
  const downOutput = await new Response(proc.stdout).text();
  const downErr = await new Response(proc.stderr).text();
  await proc.exited;

  const upProc = Bun.spawn(["docker", "compose", "up", "-d"], { cwd, stdout: "pipe", stderr: "pipe" });
  const upOutput = await new Response(upProc.stdout).text();
  const upErr = await new Response(upProc.stderr).text();
  const exitCode = await upProc.exited;

  return {
    success: exitCode === 0,
    output: [downOutput, downErr, upOutput, upErr].filter(Boolean).join("\n"),
  };
}

// ─────────────────────────────────────────────
// Extension build + install
// ─────────────────────────────────────────────

/** Build extension VSIX using bun + vsce */
export async function buildExtensionVsix(): Promise<{ success: boolean; vsixPath: string; output: string }> {
  const extensionDir = join(import.meta.dir, "../../../..", "apps/extension");
  const rootDir = join(import.meta.dir, "../../../..");

  try {
    // Step 1: Full build (webview + copy + extension)
    const build = Bun.spawn(["bun", "run", "build"], { cwd: rootDir, stdout: "pipe", stderr: "pipe" });
    const buildCode = await build.exited;
    const buildOut = await new Response(build.stdout).text();
    const buildErr = await new Response(build.stderr).text();
    if (buildCode !== 0) {
      return { success: false, vsixPath: "", output: `Build failed: ${buildErr || buildOut}` };
    }

    // Step 2: Package VSIX
    const vsce = Bun.spawn(["bunx", "@vscode/vsce", "package", "--no-dependencies"], { cwd: extensionDir, stdout: "pipe", stderr: "pipe" });
    const vsceCode = await vsce.exited;
    const vsceOut = await new Response(vsce.stdout).text();
    const vsceErr = await new Response(vsce.stderr).text();
    if (vsceCode !== 0) {
      return { success: false, vsixPath: "", output: `VSCE package failed: ${vsceErr || vsceOut}` };
    }

    // Find the built VSIX
    const pkg = JSON.parse(await Bun.file(join(extensionDir, "package.json")).text());
    const vsixPath = join(extensionDir, `hermes-ide-${pkg.version}.vsix`);

    return { success: true, vsixPath, output: vsceOut };
  } catch (e: any) {
    return { success: false, vsixPath: "", output: e.message };
  }
}

/** Install extension on a running container via docker cp + docker exec */
export async function installExtensionOnContainer(profileName: string): Promise<boolean> {
  const containerName = `hermes-ide-${profileName}`;
  const extensionDir = join(import.meta.dir, "../../../..", "apps/extension");

  // Find latest VSIX on host
  const pkg = JSON.parse(await Bun.file(join(extensionDir, "package.json")).text());
  const vsixPath = join(extensionDir, `hermes-ide-${pkg.version}.vsix`);

  if (!await Bun.file(vsixPath).exists()) {
    return false;
  }

  try {
    // Copy VSIX into container
    const cp = Bun.spawn(["docker", "cp", vsixPath, `${containerName}:/tmp/hermes-ide.vsix`], { stdout: "pipe", stderr: "pipe" });
    if (await cp.exited !== 0) return false;

    // Install inside container
    const script = `
      rm -rf /config/extensions/nusawork.hermes-ide* 2>/dev/null || true
      rm -f /config/extensions/.obsolete 2>/dev/null || true
      rm -rf /config/.local/share/code-server/extensions/nusawork.hermes-ide* 2>/dev/null || true
      /app/code-server/bin/code-server --extensions-dir /config/extensions --install-extension /tmp/hermes-ide.vsix --force
      cp -r /config/extensions/nusawork.hermes-ide-* /config/.local/share/code-server/extensions/ 2>/dev/null || true
      chown -R abc:abc /config/extensions 2>/dev/null || true
      chown -R abc:abc /config/.local/share/code-server/extensions/nusawork.hermes-ide-* 2>/dev/null || true
    `;
    const install = Bun.spawn(["docker", "exec", containerName, "sh", "-c", script], { stdout: "pipe", stderr: "pipe" });
    return await install.exited === 0;
  } catch {
    return false;
  }
}

// ─────────────────────────────────────────────
// Nginx reverse proxy config generation
// ─────────────────────────────────────────────

/**
 * Generate nginx config with:
 * - ide.app.dev.nusa.work → Auth Portal (port 51000)
 * - ide-{name}.app.dev.nusa.work → code-server container (per profile port)
 *   - location /           → code-server (port 8443 via host-mapped port)
 *   - location /mcp        → MCP systemd service on host (port 56xxx)
 *   - location /health/mcp → MCP health check
 */
export function generateNginxConfig(store: ProfileStore): string {
  const profileServerBlocks = store.profiles
    .map((profile) => {
      const subdomain = `ide-${profile.name}`;
      const mcpHostPort = profile.port + 5000;
      return `
# ${profile.name} (code-server: ${profile.port}, mcp: ${mcpHostPort})
server {
    listen 443 ssl;
    server_name ${subdomain}.${IDE_DOMAIN};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 200M;

    # MCP Server (systemd service on host)
    # Hermes Agent connects here: https://${subdomain}.${IDE_DOMAIN}/mcp
    location /mcp {
        proxy_pass http://127.0.0.1:${mcpHostPort}/mcp;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
    }

    # MCP Health check
    location = /health/mcp {
        proxy_pass http://127.0.0.1:${mcpHostPort}/health;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Code-server (default)
    location / {
        proxy_pass http://127.0.0.1:${profile.port}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Accept-Encoding gzip;
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
}`;
    })
    .join("\n");

  // Collect all server_names for the HTTP→HTTPS redirect block
  const allSubdomains = store.profiles
    .map((p) => `ide-${p.name}.${IDE_DOMAIN}`)
    .join(" ");

  return `# AUTO-GENERATED by Hermes IDE Auth Portal — DO NOT EDIT MANUALLY
# Generated at: ${new Date().toISOString()}
# Pattern: ide-{profile}.${IDE_DOMAIN}

# ──────────────────────────────────────────────
# HTTP → HTTPS redirect (all IDE subdomains)
# ──────────────────────────────────────────────
server {
    listen 80;
    server_name ${AUTH_PORTAL_DOMAIN} ${allSubdomains};
    return 301 https://$host$request_uri;
}

# ──────────────────────────────────────────────
# Auth Portal: ${AUTH_PORTAL_DOMAIN}
# ──────────────────────────────────────────────
server {
    listen 443 ssl;
    server_name ${AUTH_PORTAL_DOMAIN};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10M;

    location / {
        proxy_pass http://127.0.0.1:${AUTH_PORTAL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# ──────────────────────────────────────────────
# Code-server profiles: ide-{name}.app.dev.nusa.work
# ──────────────────────────────────────────────
${profileServerBlocks}
`;
}

export function writeNginxConfig(store: ProfileStore): void {
  const content = generateNginxConfig(store);
  writeFileSync(NGINX_TMP_PATH, content);
}

export async function reloadNginx(): Promise<{ success: boolean; output: string }> {
  // Step 1: Copy from tmp to sites-available
  const cp = Bun.spawn(["sudo", "-n", "cp", NGINX_TMP_PATH, NGINX_SITES_PATH], {
    stdout: "pipe",
    stderr: "pipe",
  });
  await cp.exited;

  // Step 2: Ensure symlink in sites-enabled
  const ln = Bun.spawn(["sudo", "-n", "ln", "-sf", NGINX_SITES_PATH, NGINX_ENABLED_PATH], {
    stdout: "pipe",
    stderr: "pipe",
  });
  await ln.exited;

  // Step 3: Test nginx config
  const test = Bun.spawn(["sudo", "-n", "nginx", "-t"], { stdout: "pipe", stderr: "pipe" });
  const testOut = await new Response(test.stderr).text(); // nginx -t outputs to stderr
  const testExit = await test.exited;

  if (testExit !== 0) {
    return { success: false, output: `nginx config test failed: ${testOut}` };
  }

  // Step 4: Reload nginx
  const reload = Bun.spawn(["sudo", "-n", "systemctl", "reload", "nginx"], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const reloadOut = await new Response(reload.stderr).text();
  const reloadExit = await reload.exited;

  return {
    success: reloadExit === 0,
    output: reloadExit === 0
      ? "Nginx config deployed and reloaded successfully"
      : `Nginx reload failed: ${reloadOut}`,
  };
}

/** Get the HTTPS IDE URL for a profile */
export function getIdeUrl(profileName: string): string {
  return `https://ide-${profileName}.${IDE_DOMAIN}/`;
}

/** Get the MCP URL for a profile (domain-based, no port needed) */
export function getMcpUrl(profileName: string): string {
  return `https://ide-${profileName}.${IDE_DOMAIN}/mcp`;
}

// ─────────────────────────────────────────────
// MCP config injection ke Hermes profiles
// ─────────────────────────────────────────────

/**
 * Inject konfigurasi MCP server `ide` ke config.yaml profil Hermes.
 * 
 * URL sekarang domain-based (tanpa port):
 *   https://ide-{name}.app.dev.nusa.work/mcp
 * 
 * Pattern ini predictable — profil baru otomatis ikut.
 */
export function injectMcpConfig(store: ProfileStore): { success: number; total: number; details: string[] } {
  const details: string[] = [];
  let success = 0;

  for (const profile of store.profiles) {
    const profileDir = join(HERMES_PROFILES_DIR, profile.name);
    const configPath = join(profileDir, "config.yaml");

    // Skip jika profil Hermes tidak exist (e.g. "default" yang cuma container tanpa agent)
    if (!existsSync(configPath)) {
      details.push(`${profile.name}: skipped — no Hermes profile`);
      success++; // Expected skip, not a failure
      continue;
    }

    const mcpUrl = getMcpUrl(profile.name);

    try {
      let configContent = readFileSync(configPath, "utf-8");

      // Regex patterns — match ide entry apapun format URL-nya (http/https, port/domain)
      const ideEntryRegex = /^\s+ide:\s*\n\s+url:\s*/m;
      const mcpServersRegex = /^mcp_servers:\s*\n/m;

      const newIdeBlock = `  ide:\n    url: "${mcpUrl}"\n    timeout: 300`;

      if (ideEntryRegex.test(configContent)) {
        // Update existing ide entry
        configContent = configContent.replace(
          /(\s+)ide:\s*\n\s+url:\s*"?[^"\n]*"?\n\s+timeout:\s*\d+/m,
          `  ide:\n    url: "${mcpUrl}"\n    timeout: 300`
        );
        details.push(`${profile.name}: updated MCP url → ${mcpUrl}`);
      } else if (mcpServersRegex.test(configContent)) {
        // mcp_servers exists but no ide entry — insert after mcp_servers:
        configContent = configContent.replace(
          /^(mcp_servers:\s*\n)/m,
          `mcp_servers:\n${newIdeBlock}\n`
        );
        details.push(`${profile.name}: added ide entry → ${mcpUrl}`);
      } else {
        // No mcp_servers at all — append
        configContent = configContent.trimEnd() + `\nmcp_servers:\n${newIdeBlock}\n`;
        details.push(`${profile.name}: created mcp_servers → ${mcpUrl}`);
      }

      writeFileSync(configPath, configContent);
      success++;
    } catch (e: any) {
      details.push(`${profile.name}: FAILED — ${e.message}`);
    }
  }

  return { success, total: store.profiles.length, details };
}

// ─────────────────────────────────────────────
// Systemd MCP Service management
// ─────────────────────────────────────────────

const MCP_ENV_DIR = "/etc/hermes-mcp";
const SYSTEMD_UNIT_SRC = join(import.meta.dir, "../../templates/mcp-hermes@.service");
const SYSTEMD_UNIT_DST = "/etc/systemd/system/mcp-hermes@.service";

/**
 * Generate per-profile env file for the MCP systemd service.
 * File: /etc/hermes-mcp/{name}.env
 * Content: MCP_PORT=56xxx
 * 
 * Writes to /tmp first, then uses sudo cp because /etc/hermes-mcp/ is root-owned.
 */
export async function generateMcpEnvFiles(store: ProfileStore): Promise<{ success: number; details: string[] }> {
  const details: string[] = [];
  let success = 0;

  // Ensure env directory exists (sudo)
  const mkdirProc = Bun.spawn(["sudo", "-n", "mkdir", "-p", MCP_ENV_DIR], { stdout: "pipe", stderr: "pipe" });
  await mkdirProc.exited;

  for (const profile of store.profiles) {
    const mcpPort = profile.port + 5000;
    const tmpPath = `/tmp/mcp-env-${profile.name}.env`;
    const envPath = join(MCP_ENV_DIR, `${profile.name}.env`);
    const content = `# Auto-generated by Hermes IDE Auth Portal\nMCP_PORT=${mcpPort}\nMCP_PROFILE=${profile.name}\n`;

    try {
      writeFileSync(tmpPath, content);
      const cp = Bun.spawn(["sudo", "-n", "cp", tmpPath, envPath], { stdout: "pipe", stderr: "pipe" });
      const cpExit = await cp.exited;
      if (cpExit !== 0) {
        const cpErr = await new Response(cp.stderr).text();
        throw new Error(`sudo cp failed: ${cpErr}`);
      }
      details.push(`${profile.name}: env → ${envPath} (port ${mcpPort})`);
      success++;
    } catch (e: any) {
      details.push(`${profile.name}: FAILED — ${e.message}`);
    }
  }

  return { success, details };
}

/**
 * Install systemd unit template and enable services for all profiles.
 * Requires sudo.
 */
export async function deployMcpServices(store: ProfileStore): Promise<{ success: boolean; output: string }> {
  const outputs: string[] = [];

  // Step 1: Copy unit template
  const templateContent = readFileSync(SYSTEMD_UNIT_SRC, "utf-8");
  const tmpPath = "/tmp/mcp-hermes@.service";
  writeFileSync(tmpPath, templateContent);

  const cp = Bun.spawn(["sudo", "-n", "cp", tmpPath, SYSTEMD_UNIT_DST], { stdout: "pipe", stderr: "pipe" });
  await cp.exited;

  // Step 2: Generate env files
  const envResult = await generateMcpEnvFiles(store);
  outputs.push(`Env files: ${envResult.success}/${store.profiles.length}`);

  // Step 3: Reload systemd daemon
  const reload = Bun.spawn(["sudo", "-n", "systemctl", "daemon-reload"], { stdout: "pipe", stderr: "pipe" });
  await reload.exited;
  outputs.push("systemd daemon reloaded");

  // Step 4: Enable and restart each profile's service
  for (const profile of store.profiles) {
    const serviceName = `mcp-hermes@${profile.name}.service`;

    const enable = Bun.spawn(["sudo", "-n", "systemctl", "enable", serviceName], { stdout: "pipe", stderr: "pipe" });
    await enable.exited;

    const restart = Bun.spawn(["sudo", "-n", "systemctl", "restart", serviceName], { stdout: "pipe", stderr: "pipe" });
    const restartErr = await new Response(restart.stderr).text();
    const restartExit = await restart.exited;

    if (restartExit === 0) {
      outputs.push(`${profile.name}: service started`);
    } else {
      outputs.push(`${profile.name}: FAILED — ${restartErr}`);
    }
  }

  return { success: true, output: outputs.join("\n") };
}

// ─────────────────────────────────────────────
// Code-server settings injection
// ─────────────────────────────────────────────

const DEFAULT_SETTINGS = {
  "workbench.startupEditor": "none",
  "workbench.colorTheme": "Default Dark Modern",
  "editor.fontSize": 14,
  "editor.minimap.enabled": false,
  "editor.wordWrap": "on",
  "files.autoSave": "afterDelay",
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/Thumbs.db": true,
    "**/.hermes": true,
    "**/node_modules": true,
    "**/.old_modules*": true,
    "**/vendor": true,
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/.old_modules*": true,
    "**/vendor": true,
    "**/.hermes": true,
    "**/storage/logs": true,
    "**/storage/framework": true,
    "**/.git": true,
    "**/dist": true,
    "**/*.vsix": true,
    "**/config-*/": true,
  },
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/.old_modules*/**": true,
    "**/vendor/**": true,
    "**/.hermes/**": true,
  },
};

/**
 * Inject VS Code settings.json into a running code-server container.
 * Ensures correct ownership (abc:abc) so code-server can read/write it.
 */
export async function injectCodeServerSettings(profileName: string): Promise<boolean> {
  const containerName = `hermes-ide-${profileName}`;
  const settingsJson = JSON.stringify(DEFAULT_SETTINGS, null, 2);
  // Escape single quotes for shell
  const escaped = settingsJson.replace(/'/g, "'\\''");

  const script = `
    mkdir -p /config/data/User
    echo '${escaped}' > /config/data/User/settings.json
    chown abc:abc /config/data/User/settings.json
    chmod 644 /config/data/User/settings.json
  `;

  const proc = Bun.spawn(["docker", "exec", containerName, "sh", "-c", script], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const exitCode = await proc.exited;
  return exitCode === 0;
}

/**
 * Inject settings into all containers.
 */
export async function injectAllCodeServerSettings(
  store: ProfileStore
): Promise<{ success: number; total: number; details: string[] }> {
  const details: string[] = [];
  let success = 0;

  for (const profile of store.profiles) {
    const ok = await injectCodeServerSettings(profile.name);
    if (ok) {
      success++;
      details.push(`${profile.name}: settings injected`);
    } else {
      details.push(`${profile.name}: settings injection FAILED`);
    }
  }

  return { success, total: store.profiles.length, details };
}

/**
 * Restart a single profile's MCP service
 */
export async function restartMcpService(profileName: string): Promise<{ success: boolean; output: string }> {
  const serviceName = `mcp-hermes@${profileName}.service`;
  const proc = Bun.spawn(["sudo", "-n", "systemctl", "restart", serviceName], { stdout: "pipe", stderr: "pipe" });
  const err = await new Response(proc.stderr).text();
  const exitCode = await proc.exited;

  return {
    success: exitCode === 0,
    output: exitCode === 0 ? `${serviceName} restarted` : `Failed: ${err}`,
  };
}
