import { writeFileSync } from "fs";
import { join } from "path";
import type { ProfileStore } from "./store";

const DOCKER_COMPOSE_PATH = join(import.meta.dir, "../../../code-server-infra/docker-compose.yml");

const CODE_SERVER_IMAGE = "lscr.io/linuxserver/code-server:latest";

export function generateDockerCompose(store: ProfileStore): string {
  const services: string[] = [];

  for (const profile of store.profiles) {
    const serviceName = `hermes-ide-${profile.name}`;
    services.push(`  ${serviceName}:
    image: ${CODE_SERVER_IMAGE}
    container_name: ${serviceName}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD=${profile.password}
      - DEFAULT_WORKSPACE=/projects
    volumes:
      - /home/ade/projects/${profile.name}:/projects
      - ./config-${profile.name}:/config
    ports:
      - "${profile.port}:8443"
    networks:
      - hermes-ide-net
    restart: unless-stopped`);
  }

  return `# AUTO-GENERATED by Auth Portal API — DO NOT EDIT MANUALLY
# Generated at: ${new Date().toISOString()}

networks:
  hermes-ide-net:
    driver: bridge

services:
${services.join("\n\n")}
`;
}

export function writeDockerCompose(store: ProfileStore): void {
  const content = generateDockerCompose(store);
  writeFileSync(DOCKER_COMPOSE_PATH, content);
}

export async function restartContainer(serviceName: string): Promise<{ success: boolean; output: string }> {
  const cwd = join(import.meta.dir, "../../../code-server-infra");
  // using --no-deps to only recreate the specified container
  const upProc = Bun.spawn(["docker", "compose", "up", "-d", "--no-deps", serviceName], { cwd, stdout: "pipe", stderr: "pipe" });
  const upOutput = await new Response(upProc.stdout).text();
  const upErr = await new Response(upProc.stderr).text();
  const exitCode = await upProc.exited;

  return {
    success: exitCode === 0,
    output: [upOutput, upErr].filter(Boolean).join("\n"),
  };
}

export async function restartContainers(): Promise<{ success: boolean; output: string }> {
  const cwd = join(import.meta.dir, "../../../code-server-infra");
  const proc = Bun.spawn(["docker", "compose", "down", "--remove-orphans"], { cwd, stdout: "pipe", stderr: "pipe" });
  const downOutput = await new Response(proc.stdout).text();
  const downErr = await new Response(proc.stderr).text();
  await proc.exited;

  const upProc = Bun.spawn(["docker", "compose", "up", "-d"], { cwd, stdout: "pipe", stderr: "pipe" });
  const upOutput = await new Response(upProc.stdout).text();
  const upErr = await new Response(upProc.stderr).text();
  const exitCode = await upProc.exited;

  return {
    success: exitCode === 0,
    output: [downOutput, downErr, upOutput, upErr].filter(Boolean).join("\n"),
  };
}